apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-profile-app
  template:
    metadata:
      labels:
        app: user-profile-app
    spec:
      containers:
      - name: user-profile-app
        image: syedwahid/user-profile-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"